# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib lenguar, .registration = TRUE
NULL

#' Initialize a new template-library git repo at `path`.
#' @noRd
rs_init <- function(path) .Call(wrap__rs_init, path)

#' Add or update a template, committing the change. Returns the commit sha.
#' @noRd
rs_add <- function(path, name, title, fields, body, message) .Call(wrap__rs_add, path, name, title, fields, body, message)

#' Render a template with variables substituted, or return its raw body.
#' @noRd
rs_get <- function(path, name, vars, raw) .Call(wrap__rs_get, path, name, vars, raw)

#' List every template in the store as a `name`/`title` data frame.
#' @noRd
rs_list <- function(path) .Call(wrap__rs_list, path)

#' Filter templates by frontmatter field (AND of all pairs in `fields`).
#' @noRd
rs_search <- function(path, fields) .Call(wrap__rs_search, path, fields)

#' Show the commit history for a template as a `commit`/`message` data frame.
#' @noRd
rs_log <- function(path, name) .Call(wrap__rs_log, path, name)

#' Diff a template's content between two revisions as a `tag`/`line` data frame.
#' @noRd
rs_diff <- function(path, name, from, to) .Call(wrap__rs_diff, path, name, from, to)

# nolint end
